const state = { chips: [], modules: [], allocation: [], risks: [] };
const $ = (id) => document.getElementById(id);
async function api(path, options = {}) {
  const response = await fetch(path, { headers: { "Content-Type": "application/json" }, ...options });
  const data = await response.json();
  if (!response.ok || data.error) throw new Error(data.error || "请求失败");
  return data;
}
function selectedModuleIds() { return [...document.querySelectorAll(".module-check:checked")].map((item) => item.value); }
function payload() { return { project_name: $("projectName").value || "demo_project", notes: $("notes").value || "", chip_id: $("chipSelect").value, module_ids: selectedModuleIds(), allocation: state.allocation }; }
async function loadChips() { const q = encodeURIComponent($("chipSearch")?.value || ""); state.chips = (await api(`/api/chips?q=${q}`)).chips; renderChips(); }
async function loadModules() { const q = encodeURIComponent($("moduleSearch")?.value || ""); const selected = new Set(selectedModuleIds()); state.modules = (await api(`/api/modules?q=${q}`)).modules; renderModules(selected); }
function renderChips() { $("chipSelect").innerHTML = state.chips.map((chip) => `<option value="${chip.id}">${chip.name} (${chip.voltage})</option>`).join(""); }
function renderModules(selected = new Set()) { $("moduleList").innerHTML = state.modules.map((module, index) => `<label class="module-item"><input class="module-check" type="checkbox" value="${module.id}" ${selected.has(module.id) || (!selected.size && index < 5) ? "checked" : ""}><span><strong>${module.name}</strong><span class="module-text">${module.description}</span></span></label>`).join(""); }
function renderAllocation() { $("allocationBody").innerHTML = state.allocation.map((item, index) => `<tr><td>${item.module_name}</td><td>${item.module_pin}</td><td><input data-index="${index}" class="pin-input" value="${item.chip_pin}"></td><td>${item.function}</td><td class="score">${item.score ?? "-"}</td><td>${item.note || ""}</td></tr>`).join(""); }
function renderRisks() { $("riskList").innerHTML = state.risks.map((risk) => { const cls = risk.level === "错误" ? "error" : risk.level === "警告" ? "warning" : "tip"; return `<div class="risk ${cls}"><strong>[${risk.level}]</strong> ${risk.message}<small>${risk.suggestion || ""}</small></div>`; }).join(""); }
function syncAllocationFromTable() { document.querySelectorAll(".pin-input").forEach((input) => { state.allocation[Number(input.dataset.index)].chip_pin = input.value.trim() || "未分配"; }); }
async function allocate() { const data = await api("/api/allocate", { method: "POST", body: JSON.stringify({ project_name: $("projectName").value, notes: $("notes").value, chip_id: $("chipSelect").value, module_ids: selectedModuleIds() }) }); state.allocation = data.allocation; state.risks = data.risks; renderAllocation(); renderRisks(); setStatus("自动分配完成"); }
async function recheck() { syncAllocationFromTable(); const data = await api("/api/allocate", { method: "POST", body: JSON.stringify(payload()) }); state.allocation = data.allocation; state.risks = data.risks; renderAllocation(); renderRisks(); setStatus("风险检查完成"); }
async function saveProject() { syncAllocationFromTable(); const data = await api("/api/save", { method: "POST", body: JSON.stringify(payload()) }); setStatus(`已保存：${data.path}`); await loadProjects(); }
async function exportFile(kind) { syncAllocationFromTable(); const endpoint = kind === "pins" ? "/api/export/pins" : `/api/export/${kind}`; const data = await api(endpoint, { method: "POST", body: JSON.stringify(payload()) }); setStatus(`已导出：${data.path}`); }
async function loadProjects() { const data = await api("/api/projects"); $("projectList").innerHTML = data.projects.map((name) => `<button class="project-item" data-name="${name}">${name}</button>`).join(""); document.querySelectorAll(".project-item").forEach((btn) => btn.addEventListener("click", async () => { const project = await api(`/api/project?name=${encodeURIComponent(btn.dataset.name)}`); $("projectName").value = project.project_name || btn.dataset.name; $("notes").value = project.notes || ""; $("chipSelect").value = project.chip_id; document.querySelectorAll(".module-check").forEach((check) => { check.checked = (project.module_ids || []).includes(check.value); }); state.allocation = project.allocation || []; await recheck(); })); }
function setStatus(text) { $("statusBox").textContent = text; }
async function init() { await Promise.all([loadChips(), loadModules()]); await loadProjects(); $("chipSearch").addEventListener("input", () => loadChips().catch((err) => setStatus(err.message))); $("moduleSearch").addEventListener("input", () => loadModules().catch((err) => setStatus(err.message))); $("allocateBtn").addEventListener("click", () => allocate().catch((err) => setStatus(err.message))); $("recheckBtn").addEventListener("click", () => recheck().catch((err) => setStatus(err.message))); $("saveBtn").addEventListener("click", () => saveProject().catch((err) => setStatus(err.message))); $("exportMdBtn").addEventListener("click", () => exportFile("markdown").catch((err) => setStatus(err.message))); $("exportPinsBtn").addEventListener("click", () => exportFile("pins").catch((err) => setStatus(err.message))); $("exportArduinoBtn").addEventListener("click", () => exportFile("arduino").catch((err) => setStatus(err.message))); $("exportStm32Btn").addEventListener("click", () => exportFile("stm32_hal").catch((err) => setStatus(err.message))); $("exportEspBtn").addEventListener("click", () => exportFile("esp_idf").catch((err) => setStatus(err.message))); $("exportKicadBtn").addEventListener("click", () => exportFile("kicad").catch((err) => setStatus(err.message))); await allocate(); }
init().catch((err) => setStatus(err.message));
